### ISSUE TITLE
where is the training data

### ISSUE THREAD

**Issue by wwqydy** [MarkWuNLP/MultiTurnResponseSelection#11]
it's a good job, you meant that you have released the douban corpus in the paper, but i couldn't find the training data in this project.

**Comment by snakeztc** [comment]
Same request. Please add training data.

**Comment by MarkWuNLP** [comment]
Please email me for the training data with your name and affiliation :)

**Comment by yangliuy** [comment]
I sent the email to you for the training data. Look forward to your reply :)

**Comment by wucz** [comment]
I've sent email to you. Look forword to your reply , thx :)

**Comment by resorcap** [comment]
Same request. And word2vec site https://1drv.ms/u/s!AtcxwlQuQjw1jF0bjeaKHEUNwitA can not visited.

**Comment by MarkWuNLP** [comment]
The accessibility of https://1drv.ms/u/s!AtcxwlQuQjw1jF0bjeaKHEUNwitA is confirmed. Everyone can download it freely.
