### ISSUE TITLE
请问word2vec.model在哪里

### ISSUE THREAD

**Issue by LiuJunhong** [MarkWuNLP/MultiTurnResponseSelection#14]
您好，按照您在readme里面写的，修改path后运行PreProcess.py提示错误，找不到word2vec.model，请问在PreProcess.py中用到的word2vec.model，以及其他文件：train.topic、mergedic2.txt等文件在哪里呢？谢谢！

**Comment by MarkWuNLP** [comment]
200d embedding and corpus is saved at https://1drv.ms/u/s!AtcxwlQuQjw1jF0bjeaKHEUNwitA

**Comment by NonvolatileMemory** [comment]
i think you can also train it with gensim on corpus

**Comment by yangliuy** [comment]
Hi, Yu, Thank you for sharing the data!  But the data in this folder is not the word embedding file. Could you share the data you used in the following two functions ? Thank you! We want to reproduce your reported results on Ubuntu data in the ACL'17 paper so that we can compare our method with your method. Look forward to your reply!

def ParseSingleTurn():
    logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
    revs, vocab, max_len = build_data(r"\\msra-sandvm-001\v-wuyu\Data\ubuntu_data\ubuntu_data\train.topic",isshuffle=True)
    word2vec = WordVecs(r"\\msra-sandvm-001\v-wuyu\Models\W2V\Ubuntu\word2vec.model", vocab, True, True)
    cPickle.dump([revs, word2vec, max_len,createtopicvec()], open("ubuntu_data.test",'wb'))
    logger.info("dataset created!")

def ParseMultiTurn():
    logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
    revs, vocab, max_len = build_multiturn_data(r"\\msra-sandvm-001\v-wuyu\Data\ubuntu_data\ubuntu_data\test.txt",isshuffle=False)
    word2vec = WordVecs(r"\\msra-sandvm-001\v-wuyu\Models\W2V\Ubuntu\word2vec.model", vocab, True, True)
    cPickle.dump([revs, word2vec, max_len], open("ubuntu_data.mul.test",'wb'))
    logger.info("dataset created!")

**Comment by yangliuy** [comment]
The shared file in https://1drv.ms/u/s!AtcxwlQuQjw1jF0bjeaKHEUNwitA is not word embedding file. Could you share the word embedding file used in your experiments ? Thank you!

**Comment by MarkWuNLP** [comment]
The shared file in https://1drv.ms/u/s!AtcxwlQuQjw1jF0bjeaKHEUNwitA contains context-response pairs, word embeddings, max_lengh. 
Every one can run it with SMN_Last.py (Please modify the parameter word_embedding_size=200 hidden_size=200 in SMN_Last.py)

**Comment by yangliuy** [comment]
@NonvolatileMemory I think you are correct. I saw you did this in your MXNET implementation of SMN. Good job.

**Comment by basma-b** [comment]
@MarkWuNLP can you provide please the scripts to build this [file](https://1drv.ms/u/s!AtcxwlQuQjw1jF0bjeaKHEUNwitA) ? 

I guess that [this function](https://github.com/MarkWuNLP/MultiTurnResponseSelection/blob/9deb56390c8e0838676839c608a97548d7d943ed/src/PreProcess.py#L146) should generate that file right ? in this case please can you provide the script to make **word2vec.model** I need to train everything from scratch and not only use the full dump you gave above.

Thanks

**Comment by wenchaodudu** [comment]
Do you have the copy of word vectors for Douban data?
