### ISSUE TITLE
Questions on running SMN_Last.py / Not work

### ISSUE THREAD

**Issue by yangliuy** [MarkWuNLP/MultiTurnResponseSelection#15]
Hi, Yu,

I followed the instructions in https://github.com/MarkWuNLP/MultiTurnResponseSelection/issues/14 to run  SMN_Last.py. But it does not work. As you suggested, I modified the parameter word_embedding_size=200 hidden_size=200 in SMN_Last.py.

The following is the error message. Do you know the reason for this? Thanks!

trainning data 949999 val data 50001
image shape (200, 2, 50, 50)
filter shape (8, 2, 3, 3)
/mnt/scratch/lyang/working/PycharmProjects/NLPIRNNMatchZooQA/src-match-zoo-lyang-dev/matchzoo/conqa/smn_yuwu_acl17/src/CNN.py:233: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
  self.output =theano.tensor.signal.pool.pool_2d(input=conv_out_tanh, ds=self.poolsize, ignore_border=True,mode="max")
(200, 50)
[[ -7.18495249e-03   1.15389853e-02  -4.65663650e-03 ...,   1.29073645e-02
    5.36817317e-03  -3.73283600e-03]
 [ -7.56547710e-04   2.52639169e-03   2.14198747e-03 ...,   1.87613393e-03
    3.13413644e-03  -1.80455989e-03]
 [  1.70666858e-02  -1.36987258e-02   2.04090084e-02 ...,   6.40176979e-03
    2.26856302e-02  -3.21805640e-02]
 ..., 
 [  1.94880138e-02   1.08157883e-03   7.03368021e-05 ...,   1.80350402e-02
   -3.28865572e-03  -1.50815454e-02]
 [  5.96401096e-03  -9.91006641e-04   4.77976783e-03 ...,   2.32200795e-02
    3.23144545e-02  -8.65365822e-03]
 [ -6.93387402e-04   3.27511476e-03   2.07571058e-03 ...,   1.42423584e-03
    3.12527304e-03   8.35354059e-04]]
Traceback (most recent call last):
  File "SMN_Last.py", line 422, in <module>
    ,hidden_size=200,word_embedding_size=200)
  File "SMN_Last.py", line 334, in train
    train_model = theano.function([index], cost,updates=grad_updates, givens=dic,on_unused_input='ignore')
  File "/usr/lib/python2.7/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/usr/lib/python2.7/site-packages/theano/compile/pfunc.py", line 449, in pfunc
    no_default_updates=no_default_updates)
  File "/usr/lib/python2.7/site-packages/theano/compile/pfunc.py", line 208, in rebuild_collect_shared
    raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=<TensorType(float32, matrix)>, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

**Comment by yuewang1402** [comment]
Sorry, I also have this problem.
Have you solved this problem? Can you tell me how to solve it?
Thank you.
