### ISSUE TITLE
请问下，关于response

### ISSUE THREAD

**Issue by guotong1988** [MarkWuNLP/MultiTurnResponseSelection#2]
response candidate r 我理解应该是固定的一句话，现在是把r这整句话一起输进SMN，

如果换成r的id会怎样？

@MarkWuNLP 谢谢！

**Comment by MarkWuNLP** [comment]
不太明白什么r的id是指什么。这里面每个conversation对应的response是不一样的，所以response并不是对于每个conversation都固定的一句话，还是需要用词语来表示这个response

**Comment by guotong1988** [comment]
谢谢您！我想问下所有response是有一个固定的库？还是可以灵活生成的？

另外，怎么做到一个问句（conversation）对应多个response的？

**Comment by guotong1988** [comment]
“这里面每个conversation对应的response是不一样的”——我理解是说一个conversation对应一个response

“所以response并不是对于每个conversation都固定的一句话”——我理解是说一个conversation对应多个response

**Comment by MarkWuNLP** [comment]
response有一个固定的库；conversation和response在正例上一一对应；但是这份源码要想跑通，不能只传id，需要传一个完整的话，否则会丢失response词的特征
