### ISSUE TITLE
Tensorflow版本输入错误

### ISSUE THREAD

**Issue by yunjianyang** [MarkWuNLP/MultiTurnResponseSelection#21]
在tensorflow版本中，actions从来没有进入到模型训练这一环节。总是把true_utt给response的placeholder。

**Comment by MarkWuNLP** [comment]
self.response_ph: np.concatenate([true_utt[low:low + n_sample]] + negs, axis=0)

negs就是action。。。

**Comment by yunjianyang** [comment]
true_utt[low:low + n_sample] 这个不是positive 的action吧，如果我没理解错的话。

**Comment by MarkWuNLP** [comment]
true_utt 是正例，negs是负例

**Comment by yunjianyang** [comment]
那action和true_utt的区别是什么呢？谢谢！

**Comment by MarkWuNLP** [comment]
action是所有回复的全集，true_utt是原始message的回复，也就是m_i对应r_i，而negs是随机的一个r_j，让m_i对应r_j。也就是true。在数据上action和true_utt是一样的，如果不考虑顺序，但是用的时候由于action里面的utterance被随机抽取了，所以达到了负采样的效果

**Comment by yunjianyang** [comment]
I see. Thanks for the explanation!
