### ISSUE TITLE
Input vocabulary size?

### ISSUE THREAD

**Issue by inigo-jauregi** [MarkWuNLP/MultiTurnResponseSelection#22]
If I'm correct the I obtain a vocabulary size larger than 600.000 distinct words from the Ubuntu dataset. That number seems very big. Do you limit the vocabulary size for the model?

**Comment by MarkWuNLP** [comment]
The vocabulary size does not influence the efficacy of a matching model (It does not have a decoder which is sensitive to vocabulary size), so I do not limit the vocabulary size.

**Comment by inigo-jauregi** [comment]
Ok thanks!
