### ISSUE TITLE
Tokenize method

### ISSUE THREAD

**Issue by mapingshuo** [MarkWuNLP/MultiTurnResponseSelection#23]
How did you tokenize the raw Douban corpus? I'm trying to test my model with new data, I need to tokenize them firstly.

**Comment by MarkWuNLP** [comment]
Hi, sorry for late replay. I used an internal Microsoft tokenizer to preprocess the data.  For the sake of Microsoft policy, I cannot share the tool with you. Do you have any good idea to address it?

**Comment by mapingshuo** [comment]
Thanks for your reply.
