### ISSUE TITLE
How many epochs does it take to train UDC?

### ISSUE THREAD

**Issue by amirvt** [MarkWuNLP/MultiTurnResponseSelection#28]
Thank you for sharing the code for your paper. I was wondering how many epochs you trained the model on Ubuntu dialogue corpus for? Was training done on a single GPU? If so, how long would a single epoch take on average?

**Comment by MarkWuNLP** [comment]
1 or 2 epochs. It is easy to fit with Adam

**Comment by amirvt** [comment]
Thanks for the response.
