### ISSUE TITLE
douban数据

### ISSUE THREAD

**Issue by hitluobin** [MarkWuNLP/MultiTurnResponseSelection#4]
你们的工作对我启发很大，在github上只看到了豆瓣数据的train sample，请问一下完整的数据会发布在哪里，何时发布哦？

**Comment by efeiefei** [comment]
同问

**Comment by exe1023** [comment]
同问

**Comment by MarkWuNLP** [comment]
发email给我吧

**Comment by exe1023** [comment]
你好，
我是在台炒WxY工程大三的W生
最近放假想W做 chatbot 硗嫱妫诰W上 survey 了一下看到你的成果X得很有d趣想要靠自己重F一下，希望可以拿到你的 data。
xx

Best Regard,
奕廷
________________________________
: MarkWuNLP [notifications@github.com]
寄件日期: 2017年7月11日 下午 03:26
至: MarkWuNLP/MultiTurnResponseSelection
副本: ~奕廷; Comment
主旨: Re: [MarkWuNLP/MultiTurnResponseSelection] douban数据 (#4)


发email给我吧

―

**Comment by hitluobin** [comment]
@MarkWuNLP 我的email: hitluobin@gmail.com。谢谢！

**Comment by dpbycicle** [comment]
@MarkWuNLP 同求，dphumor@gmail.com

**Comment by weizhenzhao** [comment]
@MarkWuNLP 
1、亲，我想问一下theano 版本的SMN_Last.py在predict的时候，预测结果是0，1？还是句子呀？
这块没太看懂。
2、还有这个test.txt文件是训练数据吗？
3、能不能发一下doban的完整数据呀?不胜感激 weizhen_zhao@163.com


十分感谢

Thanks
weizhen
