### ISSUE TITLE
请问下，数据是 一个topic 加 N条回复 的帖子，为什么最后一条回复可以当作response

### ISSUE THREAD

**Issue by guotong1988** [MarkWuNLP/MultiTurnResponseSelection#5]
如何我没有理解错的话，Ubuntu Dialogue Corpus和豆瓣数据是 一个帖子题目 加 该帖子的N条回复，
为什么前面可以当作context 以及 最后一条回复可以当作response？
十分谢谢谢谢@MarkWuNLP

**Comment by MarkWuNLP** [comment]
应该只是大家觉得这是互联网上最好的模拟对话的数据吧。当然有很多并不太算对话

**Comment by guotong1988** [comment]
嗯嗯OK
