### ISSUE TITLE
弱问下PreProcess.py里word2vec.model文件怎么能有？

### ISSUE THREAD

**Issue by guotong1988** [MarkWuNLP/MultiTurnResponseSelection#7]
这里的
https://github.com/MarkWuNLP/MultiTurnResponseSelection/blob/master/src/PreProcess.py#L149
谢谢谢谢@MarkWuNLP

**Comment by MarkWuNLP** [comment]
用python的gensim可以训练一个

**Comment by guotong1988** [comment]
哦哦，输入是所有训练用的句子？

**Comment by MarkWuNLP** [comment]
是的
