### ISSUE TITLE
您好请问下，这个Words词向量设定是要在训练中调整的吗？

### ISSUE THREAD

**Issue by guotong1988** [MarkWuNLP/MultiTurnResponseSelection#9]
https://github.com/MarkWuNLP/MultiTurnResponseSelection/blob/master/src/SMN_Dynamic.py#L95

多谢多谢@MarkWuNLP

**Comment by MarkWuNLP** [comment]
嗯 不过应该不会差距太大；如果不调整可能收敛会慢一些，不过可以更好地防止过拟合
